### PR TITLE
test: add tests for fork networks

### PR DESCRIPTION
**Pull request by unparalleled-js**
### What I did

add tests for fork support

### How I did it

`-fork` str work

### How to verify it

Get an account transaction using a forked network

### Checklist

- [ ] Passes all linting checks (pre-commit and CI jobs)
- [ ] New test cases have been added and are passing
- [ ] Documentation has been updated
- [ ] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standard (will be automatically included in the changelog)

### CODE REVIEW

**Comment by unparalleled-js** [comment]
> Was there things missed here? #20

Sorry, I wasn't caught up with main and didn't notice this. Nobody had reviewed that PR!
Yes, tests were missing. They are part of this PR.

**Review by fubuloubu — APPROVED** [review]

**Comment by fubuloubu** [comment]
wow, weird segfault

**Comment by unparalleled-js** [comment]
> wow, weird segfault

Ikr. It isn't happening locally for me. I have some things to try yet..

**Comment by unparalleled-js** [comment]
OK I figured out the issue.
The `ropsten-fork` network was used in a test and that network does not work in `eth-ape==0.2.2`; it is unreleased.
Thus, it was segfaulting, which is a little odd.
I was able to get it locally by installing eth-ape 0.2.2 and python completely crashes.

**Pull request merged**
